### ISSUE TITLE
Provide Docker image

### ISSUE THREAD

**Issue by okainov** [bmcgonag/hostUp#1]
Please provide simple "quickstart" with Docker.

Minimal required set of steps should be:
- Create minimal config file
- Do `docker-compose up`

**Comment by bmcgonag** [comment]
I've actually been looking into how to dockerize my app.  I hope to have something out for that soon.

**Comment by bmcgonag** [comment]
Finally, Dockeer image is available. 

https://hub.docker.com/repository/docker/bmcgonag/hostup
